# Generated by Django 4.1.7 on 2023-03-18 12:58

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(validators=[students.models.min_age])),
                ('course', models.CharField(choices=[('001', 'Python'), ('002', 'JavaScript')], default='002', max_length=120)),
                ('is_passed', models.BooleanField(default=True)),
                ('last_name', models.CharField(max_length=80)),
                ('address', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('height', models.DecimalField(decimal_places=2, default=150.3, max_digits=5)),
            ],
        ),
    ]
