# Generated by Django 4.1.7 on 2023-03-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(error_messages={'blank': 'Please fill the field', 'unique': 'Duplicate value'}, help_text='Please be carful this field must be unique.', max_length=150, unique=True),
        ),
    ]
