# Generated by Django 4.1.7 on 2023-04-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'db_table': 'course',
                'ordering': ['from_date', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.course'),
        ),
    ]
