# Generated by Django 4.1.7 on 2023-03-15 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
