# Generated by Django 4.1.7 on 2023-04-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_course_student_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
