# Generated by Django 4.1.7 on 2023-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_passed',
            field=models.BooleanField(default=True),
        ),
    ]
