# Generated by Django 4.1.7 on 2023-04-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_saff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_saff',
            new_name='is_staff',
        ),
    ]
